Update sync tasks to return up to 200 results; add date restriction t…
ture-karlsson/katello-publish-cvs pull request #4
Opened 2017-10-04 14:59 UTC by jdkindy

Update sync tasks to return up to 200 results; add date restriction to return more recent results.

* By default, API returns a page of 20 results. If there are more than 20 sync tasks since the last run, this introduces missed tasks.  Add per_page=200 to API call to ureturn up to 200 results.  Potential for same problem if more than 200 sync tasks have completed since the last run of the script.
* Add started_at > "8 days ago" to search string to limit results to the past 8 days (assuming script is run at least weekly). Potential for problems if script is run more than 8 days apart.

2017-10-05 06:54 UTC, ture-karlsson requested changes
Good catch! 

I actually think the per_page number should be even higher. E.g. if you have 50 repos that you sync every night but only run the script once a week, then the script will fail. It should be maybe 1000 per page?

But I don't really like the 8 days restriction. It might be perfect in your use case, I think that might break things for some users.

If you up the per_page to 1000 and remove the 8 days restriction for now, I will merge this.

2017-10-05 14:18 UTC, jdkindy commented
Made changes and squashed into one commit.

2017-10-06 11:27 UTC, ture-karlsson approved these changes

2017-10-06 11:27 UTC, merged

2017-10-06 11:29 UTC, ture-karlsson commented
Merged! Thanks @jdkindy, I'd be happy to see more pull requests.